spring.application.name=portfolio-backend

# https://randomkeygen.com/hmac-key
app.jwt.secret=TezhlH92MfGg9lBxGSW0aXTNvCYJh52frLnQUIPwIvQ=

# Todo: move (and change) url, username, and password to environment variables.
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio
spring.datasource.username=portfolio_user
spring.datasource.password=portfolio_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG