spring.profiles.active=dev
spring.application.name=portfolio-backend

spring.datasource.url=${PORTFOLIO_BACKEND_DB_URL}
spring.datasource.username=${PORTFOLIO_BACKEND_DB_USER}
spring.datasource.password=${PORTFOLIO_BACKEND_DB_PASSWORD}

# https://randomkeygen.com/hmac-key
app.jwt.secret=${PORTFOLIO_BACKEND_JWT_SECRET}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
