spring.application.name=portfolio-backend

# https://randomkeygen.com/hmac-key
app.jwt.secret=TezhlH92MfGg9lBxGSW0aXTNvCYJh52frLnQUIPwIvQ=

spring.datasource.url=${PORTFOLIO_BACKEND_DB_URL}
spring.datasource.username=${PORTFOLIO_BACKEND_DB_USER}
spring.datasource.password=${PORTFOLIO_BACKEND_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.springframework.security=DEBUG